configured services to use persistent storage volumes #LSC-24
lidofinance/terra-monitors pull request #32
Opened 2021-08-20 14:36 UTC by swelf19

2021-08-21 18:19 UTC, oopcode commented
This doesn't implement logging to disk, does it?

2021-08-21 18:20 UTC, oopcode requested changes
This doesn't implement logging to disk, does it?

2021-08-23 08:04 UTC, swelf19 commented
> This doesn't implement logging to disk, does it?

it does. its persistent named volume manged by docker daemon. By default located in `/var/lib/docker/volumes/` dir
```shell
$ docker volume inspect lidobassetexporter_grafana-storage
[
    {
        "CreatedAt": "2021-08-20T17:58:00+03:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "lidobassetexporter",
            "com.docker.compose.volume": "grafana-storage"
        },
        "Mountpoint": "/var/lib/docker/volumes/lidobassetexporter_grafana-storage/_data",
        "Name": "lidobassetexporter_grafana-storage",
        "Options": null,
        "Scope": "local"
    }
]
```
if you prefer path based volume bind, we can do it.

2021-08-23 09:23 UTC, oopcode approved these changes

2021-08-23 09:32 UTC, pr0n00gler approved these changes

2021-08-23 09:44 UTC, merged